name: Ablation Study  - Hyperparameters and LR scheduler
program: main.py
method: grid
metric:
  name: val.all.f1_micro_tuned
  goal: maximize
parameters:
  experiment:
    values:
      - mimiciii_full/plm_icd
  trainer.threshold_tuning: 
    value: true
  data: 
    value: mimiciii_full
  data.max_length:
    value: 4000
  dataset.configs.max_length_tokens: 
    value: 20000


command:
  - ${env}
  - python
  - ${program}
  - gpu=-1
  - ${args_no_hyphens}
